language: go
sudo: true
git:
  depth: 3
env:
  - DUMP=true # gommon/util/testutil.Dump

go:
  - "1.13"
  - tip

# FIXME: enable test when we get rid of referring to local go mod
install:
  - go version

script:
  - go version