# TODO: check the angular project build as well
language: go
sudo: true
git:
  depth: 3
env:
  - DUMP=true # gommon/util/testutil.Dump

go:
  - 1.9.x
  - "1.10"
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - dep ensure
  - pwd

script:
  - make install
  - make test
  # TODO: test install bhmon