# start a server, wait for it, ping it
name: pingpong
reason: pingpong
framework: na
workload: na
database: na
nodes:
  - name: srv
    type: database
  - name: cli
    type: loader
stages:
  - name: download_client
    selectors:
      - name: cli
    taks:
      - driver: shell
        shell:
          command: "wget https://github.com/benchhub/benchhub/releases/download/v0.0.1/pingclient-0.0.1.zip && unzip pingclient-0.0.1.zip"
  - name: download_server
      selectors:
        - name: srv
      taks:
        - driver: shell
          shell:
            command: "wget https://github.com/benchhub/benchhub/releases/download/v0.0.1/pingserver-0.0.1.zip && unzip pingserver-0.0.1.zip"
  - name: start_server
    selectors:
      - name: srv
    tasks:
      - background: true
        driver: shell
        shell:
          command: "pingserver 8080"
        ready:
          - driver: shell
            shell:
              command: "waitforit -w http://localhost:8080/ping"
  - name: ping_server
    selectors:
      - name: cli
    tasks:
      - driver: shell
        shell:
          command: "pingclient http://{{.Nodes.srv.Ip}}:8080"
pipelines:
  - stages:
    - download_client
    - download_server
  - stages:
    - start_server
  - stages:
    - ping_server