# A builder image that contains protoc compiler
#
# References
# - https://github.com/znly/docker-protobuf

FROM ubuntu:18.04

# TODO: need to use proxy when building docker image
# protoc
# google.golang.org/protobuf/cmd/protoc-gen-go