# start a server, wait for it, ping it
name: pingpong
owner:
  id: "1"
  name: "at15"
  # NOTE: custom yaml unmarshaler
  type: "user"
workload:
  framework: pingpong
  frameworkVersion: "0.0.1"
  database: pingpong
  databaseVersion: "0.0.1"
# NOTE: extra tag is specified in proto file using (gogoproto.moretags) = "yaml:\"nodeAssignments\""
nodeAssignments:
  - selectors:
    - role: database # NOTE: custom yaml unmarshaler
    assignment:
      name: srv
      role: database
  - selectors:
    - role: loader
    assignment:
      name: cli
      role: loader
pipelines:
  - name: download
    stages:
      - download_client
      - download_server
  - name: run_server
    stages:
      - start_server
  - name: run_workload
    stages:
      - ping_server
stages:
  - name: download_client
    selectors:
      - name: cli
    tasks:
      - driver: shell
        shell:
          command: "wget https://github.com/benchhub/benchhub/releases/download/v0.0.1/pingclient-0.0.1.zip && unzip pingclient-0.0.1.zip"
  - name: download_server
    selectors:
      - name: srv
    tasks:
      - driver: shell
        shell:
          command: "wget https://github.com/benchhub/benchhub/releases/download/v0.0.1/pingserver-0.0.1.zip && unzip pingserver-0.0.1.zip"
  - name: start_server
    background: true
    selectors:
      - name: srv
    tasks:
      - background: true
        driver: shell
        shell:
          command: "pingserver 8080"
        ready:
          tasks:
            - driver: shell
              shell:
                command: "waitforit -w http://localhost:8080/ping"
  - name: ping_server
    selectors:
      - name: cli
    tasks:
      - driver: shell
        shell:
          command: "pingclient http://{{.Nodes.srv.Ip}}:8080"
